### ISSUE TITLE
some softwares

### ISSUE THREAD

**Issue by levinit** [LewisVo/Awesome-Linux-Software#128]
some suggestion ,may you can select some(as your standard)
 (if you use archlinux,you can fiind theme by "yaourt name" )

[typora](https://typora.io/) - markdown editor  
[f.lux](https://justgetflux.com/)  -  like redshift   (gui version--xflux)
[nutstore](https://www.jianguoyun.com/)  - a cloud drive  ,support  webDAV
[pitos](https://pithos.github.io/)  -- pandora gui client 
[workflowy](https://workflowy.com/)   -- a simple style note
[pencil](http://pencil.evolus.vn/) -- a designer
[haroopad](http://pad.haroopress.com/)  -- markdown editor
[gopanda](http://pandanet-igs.com/communities/gopanda2)   -- a GO (weiqi) client (igs's client)

^^^^^^^^ too many …… my softwares list……see [here](https://github.com/levinit/itnotes/blob/master/linux/%E6%88%91%E7%9A%84%E8%BD%AF%E4%BB%B6%E5%88%97%E8%A1%A8.md)（but 。。。 in Chinse)
----forgive me for my poor english

**Comment by BruceZhang1993** [comment]
I vote for f.lux

**Comment by LewisVo** [comment]
Hi, @levinit . First of all, thank you for your suggestions. I am now considering all of them to put on the list. My standard is simple : one must be safe to use, helpful and works properly on most machines. 
@BruceZhang1993  f.lux has been in the list for a long long time since the first commit 1b7ce7ad98dea38fa89114ae45e88355adb0f061
