### ISSUE TITLE
Missing Games(Prison Architect and Dota2)

### ISSUE THREAD

**Issue by almerion** [LewisVo/Awesome-Linux-Software#160]
I play these games on Arch Linux without  any problem. You can consider add them to the list. 
And thanks for this repo. It's very helpful for newbies.

**Comment by LewisVo** [comment]
Hi there, thank you for your suggestion. However, you can see in the list I mention that games from store like Steam wont be mention. Because thousands of games on Steam are now available for Linux / SteamOs, listing them out individually would waste a ton of space. Listing some will also lead to some controversy privelege

**Comment by almerion** [comment]
Sorry buddy. I think, I missed that part. I will be more careful.

**Comment by LewisVo** [comment]
@almerion  eyy, it's totally fine ;) If you do Dota on SEA server you can add me :rofl:
