### ISSUE TITLE
Bloated

### ISSUE THREAD

**Issue by Thiht** [LewisVo/Awesome-Linux-Software#202]
This is not a list of awesome Linux software, it's a list of **every existing Linux software ever** :(

For instance, I thought I would easily find a relatively good image editor in this list and came up to this: https://github.com/LewisVo/Awesome-Linux-Software#graphics
There are **44** items in this list , including not so awesome software... I don't consider this list helpful at all since I have no idea which ones are actually good. 2 or 3 items in a few more sections ("Image Viewing", "Image Editing") would be enough and would keep the list awesome.

**Comment by LewisVo** [comment]
As i said in the list:   

>  Remember : Everything has its own quality, so there will never be anything like "best app" or "selective list" here, thank you.  

I myself run every app on this list at lease once for a certain time to make sure that they works, are maintained properly, provide a certain quality to users and safe to use. All of them are awesome, in my opinion, and it is very hard to compare since each audience may have different usage. And i'm trying to split the big category into smaller ones like you have seen with https://github.com/LewisVo/Awesome-Linux-Software#development in dc706fdc03350eb137e605461c449d514de51a4c

**Comment by LewisVo** [comment]
I hope this one will help you out 47673d3812e4d0f4e30deff31b5537de3563dadf

**Comment by Thiht** [comment]
Good to know you have started to split some sections, I think it will be better this way!

The "Development" section and 47673d3 are way easier to browse, thanks for your action :)

Great job by the way, and thank you for your dedication.

**Comment by LewisVo** [comment]
@Thiht My pleasure. I have thought about this for a long time but haven't got the time to do so recently (a busy semester and currently in final exam week :smile: )
