### ISSUE TITLE
File Manager link mixup

### ISSUE THREAD

**Issue by kyleweise** [LewisVo/Awesome-Linux-Software#210]
The links associated w/ AngrySearch and Catfish under File Manager are directing to the opposite website.

**Comment by LewisVo** [comment]
Hi @kyleweise , thank you for telling us about your problem.
As far as I am concerned: 
1. Catfish link is correct : https://launchpad.net/catfish-search . It leads to the ppa of catfish project, because catfish doesn't have an official landing site. To install you use : `sudo apt install catfish`. 
2. AngrySearch link is also correct. It leads to their github page: https://github.com/DoTheEvo/ANGRYsearch

**Comment by LewisVo** [comment]
Oh I am so sorry @kyleweise , I think I know what you mean now. Their source code link is directing to the opposite website. Fixed with 203c104c66d6cee444bc2b75abd24ede9d5666a7. Also, I moved them to Productivity / Local Search
