### ISSUE TITLE
Order applications (within categories) by popularity, or show a popularity score. 

### ISSUE THREAD

**Issue by dessalines** [LewisVo/Awesome-Linux-Software#237]
Its incredibly useful to know which applications are the most popular, for given categories (popular music players, popular terminal apps, etc). 

I know its hard to gauge popularity for certain applications, but I've created a voting site, and held a poll for linux apps a few weeks ago: https://simplevote.ml/#/poll/LYp

If you want, I could make a new poll with ALL the applications by category listed in this document, and we could post it around linux forums/subreddits and have people vote on them. 

We wouldn't even need to necessarily reorder them, but just attach the popularity score from the site (0-10) if it exists.

**Comment by LewisVo** [comment]
The problem is : how can you make sure your poll reaches enough Linux users to give you the right insights on the popularity of the applications? I have seen some big Linux news sites organizing some of the biggest polls and they all are not guaranteed to reflect the real situation. If you do a vote on Reddit , for example, /r/linux, they will tell you Unity Desktop sucks by not voting for it, but in fact it is very very popular and a lot of people who use it are not even on reddit. How do we know that we have reached the right crowd? And via what channel can we reach our crowd? Right now, I don't think there is a good option.

And do you ever think that all people (especially ordinary users, not geek) would spend their time to vote for each category. In my opinion it seems lengthy and tiring.

Also, popularity doesn't always stand for quality. Take a look at the ebook-utilities category. Although the all do the same basic job, it is really really hard to decide which of them is the best, besides the fact that some of them has a special functionality to distinguish with the rest. Maybe Evince can be the most popular since it comes with every installation of Ubuntu, but people who use it and vote for it may haven't tried other options. 

Some newcomers are doing really really good and by sorting the list with popularity, you are putting an unnecessary traction on them by impressing the readers. 

Popularity is somehow complex. App store uses downloads counts, user interactions and uninstall rates to decide the popularity of an app. Online newspapers, promote new apps and share some already famous ones  via the perception of the writers. I'm sure they don't invent Google by just counting the views only. Me? I personally want to stay neutral. This list is more like a place to discover, rather than a place to find the best or the most popular.

Your vote site: https://simplevote.ml/#/poll/LYp  is a good idea, but the data derived from it is somehow not good enough to be used. For example, it is lacking some verification. I could create endless account name and boost vote for my favorite application.

Sorry for talking so much. I once thought like you, but it just seems problematic in so many aspects. Plus, I am not being harsh, pls don't cringe away from me 😄 . I'd love to hear your feedback on this, thank you.

**Comment by dessalines** [comment]
These are fair points, popularity is a tricky thing to sort out. I wanted to show you this tool where you could create a poll if you did want to sort by popularity at some point. 

It is worth noting that currently many categories are sorted by alphabetical order, while others are not. It would probably be best to do all the categories by alphabetical.

**Comment by LewisVo** [comment]
Thank you @dessalines .
