### ISSUE TITLE
Language Parity:

### ISSUE THREAD

**Issue by SaintFenix** [LewisVo/Awesome-Linux-Software#283]
So I've been thinking about this, since it's been an issue with the translations of the master list thus far.

When we add a new software, should we require that it be added to the other lists also? Not in the list's native language, but whatever language it was originally posted? Then we could have the translators run through and fix them as they are noticed. This way the lists would be more consistent. 

- Right now I'd feel bad for those who see the zh-CN list, since it's quite a ways out of date. 
- pt-BR is fairing better, and is getting translated at a pretty rapid clip.
- es-ES being the newest is the closest to parity.

I'm not sure how feasible this is (I'm still learning Git Culture), but if it could be inserted into the contribution requirements, it may help quite a bit.

**Comment by LewisVo** [comment]
No we cannot require everyone to put on all lists because it would feel unnatural and not everyone speaks multiple languages. Keeping up with the master list has long been a voluntary work, not a requirement. Of course, it would be more consistent if every list is synced with each other. However, the bigger question is: who's gonna do it? Contributors are not full time translators and therefore, this is vonluntary work, never a requirement. Using machine or any kind of bots for translation is out of my capability. 
Also, I would like to note that even if the translated lists are not on par with the master, they still have their values. And the problem of translation not keeping up to original version does not only happen in this repo, but literally everywhere with small updates coming everyday for segments.

**Comment by SaintFenix** [comment]
Perhaps then, we could put a suggestion to consider putting it on other languages if possible then? (Sort of a feel-good, if you wouldn't mind, sort of suggestion, as opposed to a requirement.

Truthfully you wouldn't have to speak a language to put it on another list in English, the names of all the programs aren't being translated, so we could even maintain alphabetical order.

**Comment by LewisVo** [comment]
> Perhaps then, we could put a suggestion to consider putting it on other languages if possible then? Sort of a feel-good, if you wouldn't mind, sort of suggestion as opposed to a requirement.

Yes it is now in issue #196 . 

> the names of all the programs aren't being translated 

But the description is 😄

**Comment by SaintFenix** [comment]
Awesome, thanks for that. :) I'll consider this closed.

I will probably write up something small to include in the "Unsure How to contribute?" section in README. In addition to the possible inclusion of it in the proposed CONTRIBUTING.md. (I like the idea of a CONTRIBUTING.md that has a longhand explanation of how to contribute to github, since like myself, I'm sure people wouldn't mind helping but were just scared of git before.
