### ISSUE TITLE
Add cloudtag - https://cloudtag.io/

### ISSUE THREAD

**Issue by colbydray** [LewisVo/Awesome-Linux-Software#287]
cloudtag - a practical piece of software that makes it easy for you to share files with your friends, and family.

**Comment by LewisVo** [comment]
Thank you for your suggestion. Also, feel free to make a pull request for this.

**Comment by SaintFenix** [comment]
Due to this being awhile ago, I just went ahead and added Cloudtag for them. If you wish to close this issue.

**Comment by LewisVo** [comment]
Sorry, I couldn't add Cloudtag into this list. While testing the app, it works just fine. But it is too vague for me to list here. There is no information on how it is built, who built it, what the terms or policies of using it are, etc. Nothing at all.
It seems fine at first but just imagine you got some problems and have no way or nowhere to address them, which is super terrible. Or more simpler, since they stand as an intermediary between uploader and downloader, they may put some harmful softwares or viruses to the file uploaded blah blah. No one protects you from this, no policy promises you that this won't happen.
